set(_CATKIN_CURRENT_PACKAGE "project_stitch")
set(project_stitch_VERSION "0.0.0")
set(project_stitch_MAINTAINER "schleptech2 <schleptech2@todo.todo>")
set(project_stitch_PACKAGE_FORMAT "2")
set(project_stitch_BUILD_DEPENDS "roscpp" "std_msgs" "genmsg" "xmlrpcpp")
set(project_stitch_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "genmsg" "xmlrpcpp")
set(project_stitch_BUILDTOOL_DEPENDS "catkin")
set(project_stitch_BUILDTOOL_EXPORT_DEPENDS )
set(project_stitch_EXEC_DEPENDS "roscpp" "std_msgs" "genmsg" "xmlrpcpp")
set(project_stitch_RUN_DEPENDS "roscpp" "std_msgs" "genmsg" "xmlrpcpp")
set(project_stitch_TEST_DEPENDS )
set(project_stitch_DOC_DEPENDS )
set(project_stitch_URL_WEBSITE "")
set(project_stitch_URL_BUGTRACKER "")
set(project_stitch_URL_REPOSITORY "")
set(project_stitch_DEPRECATED "")