set(_CATKIN_CURRENT_PACKAGE "stitch_video_server")
set(stitch_video_server_VERSION "0.2.2")
set(stitch_video_server_MAINTAINER "Russell Toris <rctoris@wpi.edu>")
set(stitch_video_server_PACKAGE_FORMAT "2")
set(stitch_video_server_BUILD_DEPENDS "roscpp" "roslib" "cv_bridge" "image_transport" "async_web_server_cpp" "ffmpeg" "sensor_msgs")
set(stitch_video_server_BUILD_EXPORT_DEPENDS )
set(stitch_video_server_BUILDTOOL_DEPENDS "catkin")
set(stitch_video_server_BUILDTOOL_EXPORT_DEPENDS )
set(stitch_video_server_EXEC_DEPENDS "roscpp" "roslib" "cv_bridge" "image_transport" "async_web_server_cpp" "ffmpeg" "sensor_msgs")
set(stitch_video_server_RUN_DEPENDS "roscpp" "roslib" "cv_bridge" "image_transport" "async_web_server_cpp" "ffmpeg" "sensor_msgs")
set(stitch_video_server_TEST_DEPENDS )
set(stitch_video_server_DOC_DEPENDS )
set(stitch_video_server_URL_WEBSITE "http://ros.org/wiki/web_video_server")
set(stitch_video_server_URL_BUGTRACKER "https://github.com/RobotWebTools/web_video_server/issues")
set(stitch_video_server_URL_REPOSITORY "https://github.com/RobotWebTools/web_video_server")
set(stitch_video_server_DEPRECATED "")